language: "en-US"
reviews:
  path_instructions:
    - path: "content/**/*.md"
      instructions: |
        Review all markdown files and ensure that:
          - Pinout diagrams are inserted using the pinout shortcode.
          - All lists items that are sentences have a period at the end.
          - Spelling and grammar is correct.
          - Additional valid words are listed in the workspace settings file in the cSpell.words property.
          - Voltages should be described with periods, e.g. 3.3V instead of 3V3.
          - All leaf pages should be in their own folder as a page bundle
          - Device and board intro pages should always have an opening descriptive paragraph before a card with an image of the device or board
          - Require GitHub alerts instead of callout shortcodes
          - "Arduino Pro Micro" and "SparkFun Pro Micro" should always be called "Pro Micro" instead
    - path: "**/*.svg"
      instructions: |
        Review all SVG files and ensure that:
          - They are minified (using svgo or similar tool to remove comments, whitespace, and unnecessary attributes).
          - They do not contain a viewBox attribute (to ensure consistent scaling behavior).
